---
title: "Hoff Bayesian Statistics"
author: "Jesse Mu"
format:
  html: default
  revealjs:
    output-file: index-slides.html
  pdf:
    output-file: index-handout.pdf
  docx:
    output-file: index-handout.docx
---

These are (fully reproducible!) R Markdown lecture notes for @hoff2009, completed as part of a 1-semester independent study course. Only Chapters 1-8 are complete right now.

Each note includes summaries of chapter sections, with math and explanations modified for clarity and the occasional link to external resources. Many figures from the book are reproduced in a ggplot/tidyverse style, and some exercises at the end of each chapter are tackled (correctness not guaranteed).

For comprehensive solutions to all exercises in the book, see [https://hoff-exercise.kaorubb.org/](https://hoff-exercise.kaorubb.org/).

If you find an error or would like to improve the notes, please submit a PR or open an issue!

## Chapters

- [Chapter 1: Introduction and examples](1.qmd)
- [Chapter 2: Belief, probability, and exchangeability](2.qmd)
- [Chapter 3: One-parameter models](3.qmd)
- [Chapter 4: Monte Carlo approximation](4.qmd)
- [Chapter 5: The Normal Model](5.qmd)
- [Chapter 6: Posterior approximation with the Gibbs sampler](6.qmd)
- [Chapter 7: The multivariate normal model](7.qmd)
- [Chapter 8: Group comparisons and hierarchical modeling](8.qmd)
- [Chapter 9: Linear regression](9.qmd)
- [Chapter 10: Nonconjugate priors and Metropolis-Hastings algorithms](10.qmd)

## Final Project

As a small final project, R code for the basic binary relation version of the Infinite Relational Model was implemented, as described in @kemp2006.

- [Infinite Relational Model](irm.qmd)
